// <auto-generated />
using System;
using AutoService.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AutoService.Data.Migrations
{
    [DbContext(typeof(AutoServiceDbContext))]
    [Migration("20261005154840_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AutoService.Core.Entities.Appointment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CarId")
                        .HasColumnType("integer")
                        .HasColumnName("car_id");

                    b.Property<int>("ClientId")
                        .HasColumnType("integer")
                        .HasColumnName("client_id");

                    b.Property<int>("MechanicId")
                        .HasColumnType("integer")
                        .HasColumnName("mechanic_id");

                    b.Property<int>("RepairBayId")
                        .HasColumnType("integer")
                        .HasColumnName("repair_bay_id");

                    b.Property<DateTime>("ScheduledAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("scheduled_at");

                    b.Property<int>("ServiceId")
                        .HasColumnType("integer")
                        .HasColumnName("service_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.HasIndex("MechanicId");

                    b.HasIndex("RepairBayId");

                    b.HasIndex("ScheduledAt");

                    b.HasIndex("ServiceId");

                    b.HasIndex("Status");

                    b.HasIndex("CarId", "ClientId");

                    b.ToTable("appointments", null, t =>
                        {
                            t.HasComment("Записи на обслуживание");

                            t.HasCheckConstraint("ck_appointments_status", "status in ('Запланирована', 'Подтверждена', 'Отменена', 'Выполнена')");
                        });

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CarId = 1,
                            ClientId = 1,
                            MechanicId = 1,
                            RepairBayId = 1,
                            ScheduledAt = new DateTime(2026, 9, 15, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            ServiceId = 1,
                            Status = "Выполнена"
                        },
                        new
                        {
                            Id = 2,
                            CarId = 3,
                            ClientId = 2,
                            MechanicId = 1,
                            RepairBayId = 2,
                            ScheduledAt = new DateTime(2026, 10, 20, 11, 0, 0, 0, DateTimeKind.Unspecified),
                            ServiceId = 2,
                            Status = "Запланирована"
                        });
                });

            modelBuilder.Entity("AutoService.Core.Entities.Car", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CarBrandId")
                        .HasColumnType("integer")
                        .HasColumnName("car_brand_id");

                    b.Property<int>("CarCategoryId")
                        .HasColumnType("integer")
                        .HasColumnName("car_category_id");

                    b.Property<int>("ClientId")
                        .HasColumnType("integer")
                        .HasColumnName("client_id");

                    b.Property<string>("Color")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("color");

                    b.Property<string>("LicensePlate")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("license_plate");

                    b.Property<int>("ManufactureYear")
                        .HasColumnType("integer")
                        .HasColumnName("manufacture_year");

                    b.Property<int>("Mileage")
                        .HasColumnType("integer")
                        .HasColumnName("mileage");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("model");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("notes");

                    b.Property<string>("Vin")
                        .IsRequired()
                        .HasMaxLength(17)
                        .HasColumnType("character varying(17)")
                        .HasColumnName("vin");

                    b.HasKey("Id");

                    b.HasAlternateKey("Id", "ClientId")
                        .HasName("ak_cars_id_client_id");

                    b.HasIndex("CarBrandId");

                    b.HasIndex("CarCategoryId");

                    b.HasIndex("ClientId");

                    b.HasIndex("LicensePlate")
                        .IsUnique();

                    b.HasIndex("Mileage");

                    b.HasIndex("Vin")
                        .IsUnique();

                    b.ToTable("cars", null, t =>
                        {
                            t.HasComment("Автомобили");

                            t.HasCheckConstraint("ck_cars_mileage", "mileage >= 0");

                            t.HasCheckConstraint("ck_cars_vin_length", "char_length(vin) = 17");

                            t.HasCheckConstraint("ck_cars_year", "manufacture_year >= 1970 and manufacture_year <= 2100");
                        });

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CarBrandId = 1,
                            CarCategoryId = 1,
                            ClientId = 1,
                            Color = "Белый",
                            LicensePlate = "А123ВС116",
                            ManufactureYear = 2018,
                            Mileage = 82000,
                            Model = "Camry",
                            Notes = "Комплектация Comfort",
                            Vin = "JTM12345678900001"
                        },
                        new
                        {
                            Id = 2,
                            CarBrandId = 2,
                            CarCategoryId = 2,
                            ClientId = 1,
                            Color = "Серый",
                            LicensePlate = "К456ОР116",
                            ManufactureYear = 2021,
                            Mileage = 34000,
                            Model = "Sportage",
                            Vin = "XWE12345678900002"
                        },
                        new
                        {
                            Id = 3,
                            CarBrandId = 1,
                            CarCategoryId = 1,
                            ClientId = 2,
                            Color = "Синий",
                            LicensePlate = "М789ТТ116",
                            ManufactureYear = 2016,
                            Mileage = 141000,
                            Model = "Corolla",
                            Vin = "JTD12345678900003"
                        });
                });

            modelBuilder.Entity("AutoService.Core.Entities.CarBrand", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("car_brands", null, t =>
                        {
                            t.HasComment("Марки автомобилей");
                        });

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Toyota"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Kia"
                        });
                });

            modelBuilder.Entity("AutoService.Core.Entities.CarCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("car_categories", null, t =>
                        {
                            t.HasComment("Категории автомобилей");
                        });

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Легковой"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Кроссовер"
                        });
                });

            modelBuilder.Entity("AutoService.Core.Entities.Client", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("email");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("full_name");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("phone");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("FullName");

                    b.HasIndex("Phone");

                    b.ToTable("clients", null, t =>
                        {
                            t.HasComment("Клиенты");
                        });

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "smirnov@example.com",
                            FullName = "Смирнов Олег Викторович",
                            Phone = "+79001112233"
                        },
                        new
                        {
                            Id = 2,
                            Email = "orlova@example.com",
                            FullName = "Орлова Анна Игоревна",
                            Phone = "+79004445566"
                        });
                });

            modelBuilder.Entity("AutoService.Core.Entities.Department", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("departments", null, t =>
                        {
                            t.HasComment("Отделы автосервиса");
                        });

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Слесарный цех"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Кузовной цех"
                        });
                });

            modelBuilder.Entity("AutoService.Core.Entities.InspectionResult", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("BrakeState")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("brake_state");

                    b.Property<string>("ElectricalState")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("electrical_state");

                    b.Property<string>("EngineState")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("engine_state");

                    b.Property<string>("Recommendations")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("recommendations");

                    b.Property<string>("SuspensionState")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("suspension_state");

                    b.Property<int>("WorkOrderId")
                        .HasColumnType("integer")
                        .HasColumnName("work_order_id");

                    b.HasKey("Id");

                    b.HasIndex("WorkOrderId")
                        .IsUnique();

                    b.ToTable("inspection_results", null, t =>
                        {
                            t.HasComment("Результаты технического осмотра");
                        });

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BrakeState = "Износа нет",
                            ElectricalState = "Ошибок электронных систем нет",
                            EngineState = "Уровень масла ниже нормы, фильтр загрязнён",
                            Recommendations = "Повторить замену масла через 10 000 км",
                            SuspensionState = "Без замечаний",
                            WorkOrderId = 1
                        });
                });

            modelBuilder.Entity("AutoService.Core.Entities.Invoice", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("AmountBeforeDiscount")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("amount_before_discount");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at");

                    b.Property<decimal>("Discount")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("discount");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.Property<decimal>("Tax")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("tax");

                    b.Property<decimal>("TaxRate")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("tax_rate");

                    b.Property<decimal>("Total")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("total");

                    b.Property<int>("WorkOrderId")
                        .HasColumnType("integer")
                        .HasColumnName("work_order_id");

                    b.HasKey("Id");

                    b.HasIndex("WorkOrderId");

                    b.ToTable("invoices", null, t =>
                        {
                            t.HasComment("Счета");

                            t.HasCheckConstraint("ck_invoices_amount", "amount_before_discount >= 0");

                            t.HasCheckConstraint("ck_invoices_discount", "discount >= 0 and discount <= amount_before_discount");

                            t.HasCheckConstraint("ck_invoices_status", "status in ('Выставлен', 'Частично оплачен', 'Оплачен')");

                            t.HasCheckConstraint("ck_invoices_tax", "tax >= 0");

                            t.HasCheckConstraint("ck_invoices_tax_formula", "tax = round((amount_before_discount - discount) * tax_rate / 100, 2)");

                            t.HasCheckConstraint("ck_invoices_tax_rate", "tax_rate >= 0 and tax_rate <= 100");

                            t.HasCheckConstraint("ck_invoices_total", "total = amount_before_discount - discount + tax");
                        });

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AmountBeforeDiscount = 5000.00m,
                            CreatedAt = new DateTime(2026, 9, 15, 16, 0, 0, 0, DateTimeKind.Unspecified),
                            Discount = 500.00m,
                            Status = "Оплачен",
                            Tax = 900.00m,
                            TaxRate = 20.00m,
                            Total = 5400.00m,
                            WorkOrderId = 1
                        });
                });

            modelBuilder.Entity("AutoService.Core.Entities.Mechanic", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("DepartmentId")
                        .HasColumnType("integer")
                        .HasColumnName("department_id");

                    b.Property<int>("SpecializationId")
                        .HasColumnType("integer")
                        .HasColumnName("specialization_id");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("SpecializationId");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("mechanics", null, t =>
                        {
                            t.HasComment("Механики");
                        });

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DepartmentId = 1,
                            SpecializationId = 1,
                            UserId = 2
                        },
                        new
                        {
                            Id = 2,
                            DepartmentId = 2,
                            SpecializationId = 2,
                            UserId = 3
                        });
                });

            modelBuilder.Entity("AutoService.Core.Entities.MechanicSchedule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("EndsAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("ends_at");

                    b.Property<int>("MechanicId")
                        .HasColumnType("integer")
                        .HasColumnName("mechanic_id");

                    b.Property<int>("RepairBayId")
                        .HasColumnType("integer")
                        .HasColumnName("repair_bay_id");

                    b.Property<DateTime>("StartsAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("starts_at");

                    b.HasKey("Id");

                    b.HasIndex("MechanicId");

                    b.HasIndex("RepairBayId");

                    b.ToTable("mechanic_schedules", null, t =>
                        {
                            t.HasComment("Расписание механиков");

                            t.HasCheckConstraint("ck_mechanic_schedules_period", "ends_at > starts_at");
                        });

                    b.HasData(
                        new
                        {
                            Id = 1,
                            EndsAt = new DateTime(2026, 9, 15, 18, 0, 0, 0, DateTimeKind.Unspecified),
                            MechanicId = 1,
                            RepairBayId = 1,
                            StartsAt = new DateTime(2026, 9, 15, 9, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 2,
                            EndsAt = new DateTime(2026, 10, 20, 18, 0, 0, 0, DateTimeKind.Unspecified),
                            MechanicId = 1,
                            RepairBayId = 2,
                            StartsAt = new DateTime(2026, 10, 20, 9, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 3,
                            EndsAt = new DateTime(2026, 9, 16, 18, 0, 0, 0, DateTimeKind.Unspecified),
                            MechanicId = 2,
                            RepairBayId = 1,
                            StartsAt = new DateTime(2026, 9, 16, 9, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("AutoService.Core.Entities.MechanicService", b =>
                {
                    b.Property<int>("MechanicId")
                        .HasColumnType("integer")
                        .HasColumnName("mechanic_id");

                    b.Property<int>("ServiceId")
                        .HasColumnType("integer")
                        .HasColumnName("service_id");

                    b.HasKey("MechanicId", "ServiceId");

                    b.HasIndex("ServiceId");

                    b.ToTable("mechanic_services", null, t =>
                        {
                            t.HasComment("Связь механиков и услуг");
                        });

                    b.HasData(
                        new
                        {
                            MechanicId = 1,
                            ServiceId = 1
                        },
                        new
                        {
                            MechanicId = 1,
                            ServiceId = 2
                        },
                        new
                        {
                            MechanicId = 2,
                            ServiceId = 2
                        },
                        new
                        {
                            MechanicId = 2,
                            ServiceId = 3
                        });
                });

            modelBuilder.Entity("AutoService.Core.Entities.Part", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("MinQuantity")
                        .HasColumnType("integer")
                        .HasColumnName("min_quantity");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<decimal>("PurchasePrice")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("purchase_price");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer")
                        .HasColumnName("quantity");

                    b.Property<decimal>("SalePrice")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("sale_price");

                    b.Property<string>("Sku")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("sku");

                    b.Property<int>("SupplierId")
                        .HasColumnType("integer")
                        .HasColumnName("supplier_id");

                    b.HasKey("Id");

                    b.HasIndex("Quantity");

                    b.HasIndex("Sku")
                        .IsUnique();

                    b.HasIndex("SupplierId");

                    b.ToTable("parts", null, t =>
                        {
                            t.HasComment("Запчасти");

                            t.HasCheckConstraint("ck_parts_min_quantity", "min_quantity >= 0");

                            t.HasCheckConstraint("ck_parts_purchase_price", "purchase_price >= 0");

                            t.HasCheckConstraint("ck_parts_quantity", "quantity >= 0");

                            t.HasCheckConstraint("ck_parts_sale_price", "sale_price >= 0");
                        });

                    b.HasData(
                        new
                        {
                            Id = 1,
                            MinQuantity = 4,
                            Name = "Масляный фильтр",
                            PurchasePrice = 400.00m,
                            Quantity = 12,
                            SalePrice = 700.00m,
                            Sku = "FIL-001",
                            SupplierId = 1
                        },
                        new
                        {
                            Id = 2,
                            MinQuantity = 4,
                            Name = "Моторное масло 5W-30",
                            PurchasePrice = 250.00m,
                            Quantity = 10,
                            SalePrice = 450.00m,
                            Sku = "OIL-5W30",
                            SupplierId = 1
                        },
                        new
                        {
                            Id = 3,
                            MinQuantity = 4,
                            Name = "Тормозные колодки",
                            PurchasePrice = 1800.00m,
                            Quantity = 1,
                            SalePrice = 3200.00m,
                            Sku = "PAD-001",
                            SupplierId = 2
                        });
                });

            modelBuilder.Entity("AutoService.Core.Entities.Payment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("amount");

                    b.Property<int>("InvoiceId")
                        .HasColumnType("integer")
                        .HasColumnName("invoice_id");

                    b.Property<string>("Method")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("method");

                    b.Property<DateTime>("PaidAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("paid_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.Property<string>("TransactionNumber")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("transaction_number");

                    b.HasKey("Id");

                    b.HasIndex("InvoiceId");

                    b.ToTable("payments", null, t =>
                        {
                            t.HasComment("Платежи");

                            t.HasCheckConstraint("ck_payments_amount", "amount > 0");

                            t.HasCheckConstraint("ck_payments_method", "method in ('Наличные', 'Карта', 'Перевод')");

                            t.HasCheckConstraint("ck_payments_status", "status in ('Проведён', 'Отменён')");
                        });

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Amount = 5400.00m,
                            InvoiceId = 1,
                            Method = "Карта",
                            PaidAt = new DateTime(2026, 9, 15, 16, 30, 0, 0, DateTimeKind.Unspecified),
                            Status = "Проведён",
                            TransactionNumber = "TRX-20260915-0001"
                        });
                });

            modelBuilder.Entity("AutoService.Core.Entities.RepairBay", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("kind");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("repair_bays", null, t =>
                        {
                            t.HasComment("Ремонтные места");

                            t.HasCheckConstraint("ck_repair_bays_kind", "kind in ('Подъёмник', 'Диагностический пост', 'Шиномонтажная зона', 'Кузовной участок')");
                        });

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Kind = "Подъёмник",
                            Name = "Подъёмник 1"
                        },
                        new
                        {
                            Id = 2,
                            Kind = "Диагностический пост",
                            Name = "Диагностический пост 1"
                        });
                });

            modelBuilder.Entity("AutoService.Core.Entities.Review", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ClientId")
                        .HasColumnType("integer")
                        .HasColumnName("client_id");

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("comment");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("Rating")
                        .HasColumnType("integer")
                        .HasColumnName("rating");

                    b.Property<int>("WorkOrderId")
                        .HasColumnType("integer")
                        .HasColumnName("work_order_id");

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.HasIndex("WorkOrderId")
                        .IsUnique();

                    b.ToTable("reviews", null, t =>
                        {
                            t.HasComment("Отзывы клиентов");

                            t.HasCheckConstraint("ck_reviews_rating", "rating >= 1 and rating <= 5");
                        });

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ClientId = 1,
                            Comment = "Заменили масло быстро, объяснили состояние фильтра.",
                            CreatedAt = new DateTime(2026, 9, 16, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            Rating = 5,
                            WorkOrderId = 1
                        });
                });

            modelBuilder.Entity("AutoService.Core.Entities.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("roles", null, t =>
                        {
                            t.HasComment("Роли пользователей");
                        });

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Администратор"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Механик"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Руководитель"
                        });
                });

            modelBuilder.Entity("AutoService.Core.Entities.Service", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("BasePrice")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("base_price");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("description");

                    b.Property<int>("DurationMinutes")
                        .HasColumnType("integer")
                        .HasColumnName("duration_minutes");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.HasIndex("BasePrice");

                    b.HasIndex("DurationMinutes");

                    b.ToTable("services", null, t =>
                        {
                            t.HasComment("Услуги");

                            t.HasCheckConstraint("ck_services_duration", "duration_minutes > 0");

                            t.HasCheckConstraint("ck_services_price", "base_price >= 0");
                        });

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BasePrice = 2500.00m,
                            Description = "Замена моторного масла и фильтра",
                            DurationMinutes = 40,
                            Name = "Замена масла"
                        },
                        new
                        {
                            Id = 2,
                            BasePrice = 1800.00m,
                            Description = "Считывание кодов ошибок электронных систем",
                            DurationMinutes = 30,
                            Name = "Компьютерная диагностика"
                        },
                        new
                        {
                            Id = 3,
                            BasePrice = 4200.00m,
                            Description = "Замена колодок передней оси",
                            DurationMinutes = 90,
                            Name = "Замена тормозных колодок"
                        });
                });

            modelBuilder.Entity("AutoService.Core.Entities.Specialization", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("specializations", null, t =>
                        {
                            t.HasComment("Специализации механиков");
                        });

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Моторист"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Автоэлектрик"
                        });
                });

            modelBuilder.Entity("AutoService.Core.Entities.Supplier", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("email");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("Phone")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("phone");

                    b.HasKey("Id");

                    b.ToTable("suppliers", null, t =>
                        {
                            t.HasComment("Поставщики");
                        });

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "sales@avtodetal.example",
                            Name = "ООО «АвтоДеталь»",
                            Phone = "+78432001122"
                        },
                        new
                        {
                            Id = 2,
                            Email = "karimov@example.com",
                            Name = "ИП Каримов",
                            Phone = "+79037654321"
                        });
                });

            modelBuilder.Entity("AutoService.Core.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("full_name");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("login");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("password_hash");

                    b.Property<int>("RoleId")
                        .HasColumnType("integer")
                        .HasColumnName("role_id");

                    b.HasKey("Id");

                    b.HasIndex("Login")
                        .IsUnique();

                    b.HasIndex("RoleId");

                    b.ToTable("users", null, t =>
                        {
                            t.HasComment("Учётные записи сотрудников");
                        });

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FullName = "Иванова Мария Сергеевна",
                            Login = "admin",
                            PasswordHash = "100000.wZ5QTl7cXQpyQmhIilnjWQ==.DxQJHW9gnwkPa5t238+TMDp8s1VcYxrqyJYD+WXmPj0=",
                            RoleId = 1
                        },
                        new
                        {
                            Id = 2,
                            FullName = "Петров Алексей Николаевич",
                            Login = "mechanic",
                            PasswordHash = "100000.iJdt0NmOptI11TdkBWEijQ==.62sQBvA3e2mayKIGA6Dvu9Z7dieB1zcJ66nM7VaOH24=",
                            RoleId = 2
                        },
                        new
                        {
                            Id = 3,
                            FullName = "Сидоров Игорь Павлович",
                            Login = "mechanic2",
                            PasswordHash = "100000.Vvp5eKSeh5T+/+EILLQ21A==.ZfLw5GRwr6I1pxnouKpJBYYFXF9KhL/BkwXUXGhOhYQ=",
                            RoleId = 2
                        },
                        new
                        {
                            Id = 4,
                            FullName = "Кузнецов Дмитрий Андреевич",
                            Login = "chief",
                            PasswordHash = "100000.D6Lp8Yio5nVp9seRgACV3Q==.TI4C15pFIO6Tx8659NCj6lc2qraufXW399Ly7eNRh0Q=",
                            RoleId = 3
                        });
                });

            modelBuilder.Entity("AutoService.Core.Entities.WorkOrder", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AppointmentId")
                        .HasColumnType("integer")
                        .HasColumnName("appointment_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("FaultDescription")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("fault_description");

                    b.Property<int>("MechanicId")
                        .HasColumnType("integer")
                        .HasColumnName("mechanic_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.HasIndex("AppointmentId")
                        .IsUnique();

                    b.HasIndex("CreatedAt");

                    b.HasIndex("MechanicId");

                    b.HasIndex("Status");

                    b.ToTable("work_orders", null, t =>
                        {
                            t.HasComment("Заказ-наряды");

                            t.HasCheckConstraint("ck_work_orders_status", "status in ('Создан', 'Диагностика', 'В ремонте', 'Завершён', 'Отменён')");
                        });

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AppointmentId = 1,
                            CreatedAt = new DateTime(2026, 9, 15, 10, 20, 0, 0, DateTimeKind.Unspecified),
                            FaultDescription = "Пониженный уровень моторного масла, загрязнён масляный фильтр.",
                            MechanicId = 1,
                            Status = "Завершён"
                        });
                });

            modelBuilder.Entity("AutoService.Core.Entities.WorkOrderPart", b =>
                {
                    b.Property<int>("WorkOrderId")
                        .HasColumnType("integer")
                        .HasColumnName("work_order_id");

                    b.Property<int>("PartId")
                        .HasColumnType("integer")
                        .HasColumnName("part_id");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer")
                        .HasColumnName("quantity");

                    b.Property<decimal>("UnitPrice")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("unit_price");

                    b.HasKey("WorkOrderId", "PartId");

                    b.HasIndex("PartId");

                    b.ToTable("work_order_parts", null, t =>
                        {
                            t.HasComment("Запчасти в заказ-нарядах");

                            t.HasCheckConstraint("ck_work_order_parts_price", "unit_price >= 0");

                            t.HasCheckConstraint("ck_work_order_parts_quantity", "quantity > 0");
                        });

                    b.HasData(
                        new
                        {
                            WorkOrderId = 1,
                            PartId = 1,
                            Quantity = 1,
                            UnitPrice = 700.00m
                        },
                        new
                        {
                            WorkOrderId = 1,
                            PartId = 2,
                            Quantity = 4,
                            UnitPrice = 450.00m
                        });
                });

            modelBuilder.Entity("AutoService.Core.Entities.WorkOrderService", b =>
                {
                    b.Property<int>("WorkOrderId")
                        .HasColumnType("integer")
                        .HasColumnName("work_order_id");

                    b.Property<int>("ServiceId")
                        .HasColumnType("integer")
                        .HasColumnName("service_id");

                    b.Property<decimal>("Price")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("price");

                    b.HasKey("WorkOrderId", "ServiceId");

                    b.HasIndex("ServiceId");

                    b.ToTable("work_order_services", null, t =>
                        {
                            t.HasComment("Услуги в заказ-нарядах");

                            t.HasCheckConstraint("ck_work_order_services_price", "price >= 0");
                        });

                    b.HasData(
                        new
                        {
                            WorkOrderId = 1,
                            ServiceId = 1,
                            Price = 2500.00m
                        });
                });

            modelBuilder.Entity("AutoService.Core.Entities.Appointment", b =>
                {
                    b.HasOne("AutoService.Core.Entities.Client", "Client")
                        .WithMany("Appointments")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AutoService.Core.Entities.Mechanic", "Mechanic")
                        .WithMany("Appointments")
                        .HasForeignKey("MechanicId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AutoService.Core.Entities.RepairBay", "RepairBay")
                        .WithMany("Appointments")
                        .HasForeignKey("RepairBayId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AutoService.Core.Entities.Service", "Service")
                        .WithMany("Appointments")
                        .HasForeignKey("ServiceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AutoService.Core.Entities.Car", "Car")
                        .WithMany("Appointments")
                        .HasForeignKey("CarId", "ClientId")
                        .HasPrincipalKey("Id", "ClientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Car");

                    b.Navigation("Client");

                    b.Navigation("Mechanic");

                    b.Navigation("RepairBay");

                    b.Navigation("Service");
                });

            modelBuilder.Entity("AutoService.Core.Entities.Car", b =>
                {
                    b.HasOne("AutoService.Core.Entities.CarBrand", "Brand")
                        .WithMany("Cars")
                        .HasForeignKey("CarBrandId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AutoService.Core.Entities.CarCategory", "Category")
                        .WithMany("Cars")
                        .HasForeignKey("CarCategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AutoService.Core.Entities.Client", "Client")
                        .WithMany("Cars")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Brand");

                    b.Navigation("Category");

                    b.Navigation("Client");
                });

            modelBuilder.Entity("AutoService.Core.Entities.InspectionResult", b =>
                {
                    b.HasOne("AutoService.Core.Entities.WorkOrder", "WorkOrder")
                        .WithOne("Inspection")
                        .HasForeignKey("AutoService.Core.Entities.InspectionResult", "WorkOrderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("WorkOrder");
                });

            modelBuilder.Entity("AutoService.Core.Entities.Invoice", b =>
                {
                    b.HasOne("AutoService.Core.Entities.WorkOrder", "WorkOrder")
                        .WithMany("Invoices")
                        .HasForeignKey("WorkOrderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("WorkOrder");
                });

            modelBuilder.Entity("AutoService.Core.Entities.Mechanic", b =>
                {
                    b.HasOne("AutoService.Core.Entities.Department", "Department")
                        .WithMany("Mechanics")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AutoService.Core.Entities.Specialization", "Specialization")
                        .WithMany("Mechanics")
                        .HasForeignKey("SpecializationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AutoService.Core.Entities.User", "User")
                        .WithOne("Mechanic")
                        .HasForeignKey("AutoService.Core.Entities.Mechanic", "UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Department");

                    b.Navigation("Specialization");

                    b.Navigation("User");
                });

            modelBuilder.Entity("AutoService.Core.Entities.MechanicSchedule", b =>
                {
                    b.HasOne("AutoService.Core.Entities.Mechanic", "Mechanic")
                        .WithMany("Schedules")
                        .HasForeignKey("MechanicId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AutoService.Core.Entities.RepairBay", "RepairBay")
                        .WithMany("Schedules")
                        .HasForeignKey("RepairBayId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Mechanic");

                    b.Navigation("RepairBay");
                });

            modelBuilder.Entity("AutoService.Core.Entities.MechanicService", b =>
                {
                    b.HasOne("AutoService.Core.Entities.Mechanic", "Mechanic")
                        .WithMany("Services")
                        .HasForeignKey("MechanicId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AutoService.Core.Entities.Service", "Service")
                        .WithMany("Mechanics")
                        .HasForeignKey("ServiceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Mechanic");

                    b.Navigation("Service");
                });

            modelBuilder.Entity("AutoService.Core.Entities.Part", b =>
                {
                    b.HasOne("AutoService.Core.Entities.Supplier", "Supplier")
                        .WithMany("Parts")
                        .HasForeignKey("SupplierId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Supplier");
                });

            modelBuilder.Entity("AutoService.Core.Entities.Payment", b =>
                {
                    b.HasOne("AutoService.Core.Entities.Invoice", "Invoice")
                        .WithMany("Payments")
                        .HasForeignKey("InvoiceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Invoice");
                });

            modelBuilder.Entity("AutoService.Core.Entities.Review", b =>
                {
                    b.HasOne("AutoService.Core.Entities.Client", "Client")
                        .WithMany("Reviews")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AutoService.Core.Entities.WorkOrder", "WorkOrder")
                        .WithOne("Review")
                        .HasForeignKey("AutoService.Core.Entities.Review", "WorkOrderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Client");

                    b.Navigation("WorkOrder");
                });

            modelBuilder.Entity("AutoService.Core.Entities.User", b =>
                {
                    b.HasOne("AutoService.Core.Entities.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("AutoService.Core.Entities.WorkOrder", b =>
                {
                    b.HasOne("AutoService.Core.Entities.Appointment", "Appointment")
                        .WithOne("WorkOrder")
                        .HasForeignKey("AutoService.Core.Entities.WorkOrder", "AppointmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AutoService.Core.Entities.Mechanic", "Mechanic")
                        .WithMany("WorkOrders")
                        .HasForeignKey("MechanicId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Appointment");

                    b.Navigation("Mechanic");
                });

            modelBuilder.Entity("AutoService.Core.Entities.WorkOrderPart", b =>
                {
                    b.HasOne("AutoService.Core.Entities.Part", "Part")
                        .WithMany("WorkOrderLines")
                        .HasForeignKey("PartId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AutoService.Core.Entities.WorkOrder", "WorkOrder")
                        .WithMany("Parts")
                        .HasForeignKey("WorkOrderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Part");

                    b.Navigation("WorkOrder");
                });

            modelBuilder.Entity("AutoService.Core.Entities.WorkOrderService", b =>
                {
                    b.HasOne("AutoService.Core.Entities.Service", "Service")
                        .WithMany("WorkOrderLines")
                        .HasForeignKey("ServiceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AutoService.Core.Entities.WorkOrder", "WorkOrder")
                        .WithMany("Services")
                        .HasForeignKey("WorkOrderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Service");

                    b.Navigation("WorkOrder");
                });

            modelBuilder.Entity("AutoService.Core.Entities.Appointment", b =>
                {
                    b.Navigation("WorkOrder");
                });

            modelBuilder.Entity("AutoService.Core.Entities.Car", b =>
                {
                    b.Navigation("Appointments");
                });

            modelBuilder.Entity("AutoService.Core.Entities.CarBrand", b =>
                {
                    b.Navigation("Cars");
                });

            modelBuilder.Entity("AutoService.Core.Entities.CarCategory", b =>
                {
                    b.Navigation("Cars");
                });

            modelBuilder.Entity("AutoService.Core.Entities.Client", b =>
                {
                    b.Navigation("Appointments");

                    b.Navigation("Cars");

                    b.Navigation("Reviews");
                });

            modelBuilder.Entity("AutoService.Core.Entities.Department", b =>
                {
                    b.Navigation("Mechanics");
                });

            modelBuilder.Entity("AutoService.Core.Entities.Invoice", b =>
                {
                    b.Navigation("Payments");
                });

            modelBuilder.Entity("AutoService.Core.Entities.Mechanic", b =>
                {
                    b.Navigation("Appointments");

                    b.Navigation("Schedules");

                    b.Navigation("Services");

                    b.Navigation("WorkOrders");
                });

            modelBuilder.Entity("AutoService.Core.Entities.Part", b =>
                {
                    b.Navigation("WorkOrderLines");
                });

            modelBuilder.Entity("AutoService.Core.Entities.RepairBay", b =>
                {
                    b.Navigation("Appointments");

                    b.Navigation("Schedules");
                });

            modelBuilder.Entity("AutoService.Core.Entities.Role", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("AutoService.Core.Entities.Service", b =>
                {
                    b.Navigation("Appointments");

                    b.Navigation("Mechanics");

                    b.Navigation("WorkOrderLines");
                });

            modelBuilder.Entity("AutoService.Core.Entities.Specialization", b =>
                {
                    b.Navigation("Mechanics");
                });

            modelBuilder.Entity("AutoService.Core.Entities.Supplier", b =>
                {
                    b.Navigation("Parts");
                });

            modelBuilder.Entity("AutoService.Core.Entities.User", b =>
                {
                    b.Navigation("Mechanic");
                });

            modelBuilder.Entity("AutoService.Core.Entities.WorkOrder", b =>
                {
                    b.Navigation("Inspection");

                    b.Navigation("Invoices");

                    b.Navigation("Parts");

                    b.Navigation("Review");

                    b.Navigation("Services");
                });
#pragma warning restore 612, 618
        }
    }
}
