using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace ProductionSystem.Data.Migrations
{
    /// <inheritdoc />
    public partial class InventorySurrogateKeys : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql("""
                ALTER TABLE materials DROP CONSTRAINT "PK_materials";
                ALTER TABLE materials ADD COLUMN "Id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL;
                ALTER TABLE materials ADD CONSTRAINT "PK_materials" PRIMARY KEY ("Id");
                CREATE UNIQUE INDEX "IX_materials_Article_WarehouseId" ON materials ("Article", "WarehouseId");
                """);

            migrationBuilder.Sql("""
                ALTER TABLE components DROP CONSTRAINT "PK_components";
                ALTER TABLE components ADD COLUMN "Id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL;
                ALTER TABLE components ADD CONSTRAINT "PK_components" PRIMARY KEY ("Id");
                CREATE INDEX "IX_components_Article_WarehouseId" ON components ("Article", "WarehouseId");
                """);
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql("""DROP INDEX "IX_materials_Article_WarehouseId";""");
            migrationBuilder.Sql("""ALTER TABLE materials DROP CONSTRAINT "PK_materials";""");
            migrationBuilder.Sql("""ALTER TABLE materials DROP COLUMN "Id";""");
            migrationBuilder.Sql("""ALTER TABLE materials ADD CONSTRAINT "PK_materials" PRIMARY KEY ("Article");""");

            migrationBuilder.Sql("""DROP INDEX "IX_components_Article_WarehouseId";""");
            migrationBuilder.Sql("""ALTER TABLE components DROP CONSTRAINT "PK_components";""");
            migrationBuilder.Sql("""ALTER TABLE components DROP COLUMN "Id";""");
            migrationBuilder.Sql("""ALTER TABLE components ADD CONSTRAINT "PK_components" PRIMARY KEY ("Article");""");
        }
    }
}
