// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using ProductionSystem.Data;

#nullable disable

namespace ProductionSystem.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ProductionSystem.Data.AppUser", b =>
                {
                    b.Property<string>("Login")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("FullName")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<byte[]>("Photo")
                        .HasColumnType("bytea");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.HasKey("Login");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("ProductionSystem.Data.CustomerOrder", b =>
                {
                    b.Property<string>("Number")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<byte[]>("CustomerDrawings")
                        .HasColumnType("bytea");

                    b.Property<string>("CustomerLogin")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<decimal?>("EstimatedCost")
                        .HasColumnType("numeric");

                    b.Property<string>("ManagerLogin")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateOnly>("OrderDate")
                        .HasColumnType("date");

                    b.Property<string>("OrderName")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<DateOnly?>("PlannedCompletionDate")
                        .HasColumnType("date");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.HasKey("Number");

                    b.HasIndex("CustomerLogin");

                    b.HasIndex("ManagerLogin");

                    b.HasIndex("ProductName");

                    b.ToTable("customer_orders", (string)null);
                });

            modelBuilder.Entity("ProductionSystem.Data.Equipment", b =>
                {
                    b.Property<string>("Marking")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("Characteristics")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<string>("EquipmentTypeName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Marking");

                    b.HasIndex("EquipmentTypeName");

                    b.ToTable("equipment", (string)null);
                });

            modelBuilder.Entity("ProductionSystem.Data.EquipmentType", b =>
                {
                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Name");

                    b.ToTable("equipment_types", (string)null);
                });

            modelBuilder.Entity("ProductionSystem.Data.Material", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Article")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("Characteristics")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<string>("Gost")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<byte[]>("Image")
                        .HasColumnType("bytea");

                    b.Property<decimal?>("Length")
                        .HasColumnType("numeric");

                    b.Property<string>("MaterialType")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.Property<decimal>("PurchasePrice")
                        .HasColumnType("numeric");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("numeric");

                    b.Property<int?>("SupplierId")
                        .HasColumnType("integer");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<int>("WarehouseId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("SupplierId");

                    b.HasIndex("WarehouseId");

                    b.HasIndex("Article", "WarehouseId")
                        .IsUnique();

                    b.ToTable("materials", (string)null);
                });

            modelBuilder.Entity("ProductionSystem.Data.Product", b =>
                {
                    b.Property<string>("Name")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<string>("Dimensions")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.HasKey("Name");

                    b.ToTable("products", (string)null);
                });

            modelBuilder.Entity("ProductionSystem.Data.ProductAssemblySpec", b =>
                {
                    b.Property<string>("ParentProductName")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<string>("ChildProductName")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("numeric");

                    b.HasKey("ParentProductName", "ChildProductName");

                    b.HasIndex("ChildProductName");

                    b.ToTable("product_assembly_specs", (string)null);
                });

            modelBuilder.Entity("ProductionSystem.Data.ProductComponentSpec", b =>
                {
                    b.Property<string>("ProductName")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<int>("ComponentId")
                        .HasColumnType("integer");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("numeric");

                    b.HasKey("ProductName", "ComponentId");

                    b.HasIndex("ComponentId");

                    b.ToTable("product_component_specs", (string)null);
                });

            modelBuilder.Entity("ProductionSystem.Data.ProductMaterialSpec", b =>
                {
                    b.Property<string>("ProductName")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<int>("MaterialId")
                        .HasColumnType("integer");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("numeric");

                    b.HasKey("ProductName", "MaterialId");

                    b.HasIndex("MaterialId");

                    b.ToTable("product_material_specs", (string)null);
                });

            modelBuilder.Entity("ProductionSystem.Data.ProductOperationSpec", b =>
                {
                    b.Property<string>("ProductName")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<int>("OperationId")
                        .HasColumnType("integer");

                    b.Property<int>("SequenceNumber")
                        .HasColumnType("integer");

                    b.Property<int>("DurationMinutes")
                        .HasColumnType("integer");

                    b.Property<string>("EquipmentTypeName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("ProductName", "OperationId", "SequenceNumber");

                    b.HasIndex("EquipmentTypeName");

                    b.HasIndex("OperationId");

                    b.ToTable("product_operation_specs", (string)null);
                });

            modelBuilder.Entity("ProductionSystem.Data.ProductionOperation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("production_operations", (string)null);
                });

            modelBuilder.Entity("ProductionSystem.Data.StockComponent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Article")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("ComponentType")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<byte[]>("Image")
                        .HasColumnType("bytea");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.Property<decimal>("PurchasePrice")
                        .HasColumnType("numeric");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("numeric");

                    b.Property<int?>("SupplierId")
                        .HasColumnType("integer");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<int>("WarehouseId")
                        .HasColumnType("integer");

                    b.Property<decimal>("Weight")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("SupplierId");

                    b.HasIndex("WarehouseId");

                    b.HasIndex("Article", "WarehouseId");

                    b.ToTable("components", (string)null);
                });

            modelBuilder.Entity("ProductionSystem.Data.Supplier", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasColumnType("text");

                    b.Property<int>("DeliveryDays")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("suppliers", (string)null);
                });

            modelBuilder.Entity("ProductionSystem.Data.Warehouse", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.ToTable("warehouses", (string)null);
                });

            modelBuilder.Entity("ProductionSystem.Data.Worker", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateOnly>("BirthDate")
                        .HasColumnType("date");

                    b.Property<string>("Education")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<string>("FirstMiddleName")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<string>("HomeAddress")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("Qualification")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.HasKey("Id");

                    b.ToTable("workers", (string)null);
                });

            modelBuilder.Entity("ProductionSystem.Data.WorkerOperation", b =>
                {
                    b.Property<int>("WorkerId")
                        .HasColumnType("integer");

                    b.Property<int>("OperationId")
                        .HasColumnType("integer");

                    b.HasKey("WorkerId", "OperationId");

                    b.HasIndex("OperationId");

                    b.ToTable("worker_operations", (string)null);
                });

            modelBuilder.Entity("ProductionSystem.Data.CustomerOrder", b =>
                {
                    b.HasOne("ProductionSystem.Data.AppUser", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerLogin")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ProductionSystem.Data.AppUser", "Manager")
                        .WithMany()
                        .HasForeignKey("ManagerLogin")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("ProductionSystem.Data.Product", "Product")
                        .WithMany("CustomerOrders")
                        .HasForeignKey("ProductName")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Customer");

                    b.Navigation("Manager");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("ProductionSystem.Data.Equipment", b =>
                {
                    b.HasOne("ProductionSystem.Data.EquipmentType", "EquipmentType")
                        .WithMany("Equipment")
                        .HasForeignKey("EquipmentTypeName")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("EquipmentType");
                });

            modelBuilder.Entity("ProductionSystem.Data.Material", b =>
                {
                    b.HasOne("ProductionSystem.Data.Supplier", "Supplier")
                        .WithMany("Materials")
                        .HasForeignKey("SupplierId");

                    b.HasOne("ProductionSystem.Data.Warehouse", "Warehouse")
                        .WithMany("Materials")
                        .HasForeignKey("WarehouseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Supplier");

                    b.Navigation("Warehouse");
                });

            modelBuilder.Entity("ProductionSystem.Data.ProductAssemblySpec", b =>
                {
                    b.HasOne("ProductionSystem.Data.Product", "ChildProduct")
                        .WithMany("AssemblyParents")
                        .HasForeignKey("ChildProductName")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ProductionSystem.Data.Product", "ParentProduct")
                        .WithMany("AssemblyChildren")
                        .HasForeignKey("ParentProductName")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ChildProduct");

                    b.Navigation("ParentProduct");
                });

            modelBuilder.Entity("ProductionSystem.Data.ProductComponentSpec", b =>
                {
                    b.HasOne("ProductionSystem.Data.StockComponent", "Component")
                        .WithMany()
                        .HasForeignKey("ComponentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProductionSystem.Data.Product", "Product")
                        .WithMany("ComponentSpecs")
                        .HasForeignKey("ProductName")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Component");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("ProductionSystem.Data.ProductMaterialSpec", b =>
                {
                    b.HasOne("ProductionSystem.Data.Material", "Material")
                        .WithMany()
                        .HasForeignKey("MaterialId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProductionSystem.Data.Product", "Product")
                        .WithMany("MaterialSpecs")
                        .HasForeignKey("ProductName")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Material");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("ProductionSystem.Data.ProductOperationSpec", b =>
                {
                    b.HasOne("ProductionSystem.Data.EquipmentType", "EquipmentType")
                        .WithMany("OperationSpecs")
                        .HasForeignKey("EquipmentTypeName")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("ProductionSystem.Data.ProductionOperation", "Operation")
                        .WithMany("ProductOperationSpecs")
                        .HasForeignKey("OperationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ProductionSystem.Data.Product", "Product")
                        .WithMany("OperationSpecs")
                        .HasForeignKey("ProductName")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EquipmentType");

                    b.Navigation("Operation");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("ProductionSystem.Data.StockComponent", b =>
                {
                    b.HasOne("ProductionSystem.Data.Supplier", "Supplier")
                        .WithMany("Components")
                        .HasForeignKey("SupplierId");

                    b.HasOne("ProductionSystem.Data.Warehouse", "Warehouse")
                        .WithMany("Components")
                        .HasForeignKey("WarehouseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Supplier");

                    b.Navigation("Warehouse");
                });

            modelBuilder.Entity("ProductionSystem.Data.WorkerOperation", b =>
                {
                    b.HasOne("ProductionSystem.Data.ProductionOperation", "Operation")
                        .WithMany("WorkerOperations")
                        .HasForeignKey("OperationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProductionSystem.Data.Worker", "Worker")
                        .WithMany("WorkerOperations")
                        .HasForeignKey("WorkerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Operation");

                    b.Navigation("Worker");
                });

            modelBuilder.Entity("ProductionSystem.Data.EquipmentType", b =>
                {
                    b.Navigation("Equipment");

                    b.Navigation("OperationSpecs");
                });

            modelBuilder.Entity("ProductionSystem.Data.Product", b =>
                {
                    b.Navigation("AssemblyChildren");

                    b.Navigation("AssemblyParents");

                    b.Navigation("ComponentSpecs");

                    b.Navigation("CustomerOrders");

                    b.Navigation("MaterialSpecs");

                    b.Navigation("OperationSpecs");
                });

            modelBuilder.Entity("ProductionSystem.Data.ProductionOperation", b =>
                {
                    b.Navigation("ProductOperationSpecs");

                    b.Navigation("WorkerOperations");
                });

            modelBuilder.Entity("ProductionSystem.Data.Supplier", b =>
                {
                    b.Navigation("Components");

                    b.Navigation("Materials");
                });

            modelBuilder.Entity("ProductionSystem.Data.Warehouse", b =>
                {
                    b.Navigation("Components");

                    b.Navigation("Materials");
                });

            modelBuilder.Entity("ProductionSystem.Data.Worker", b =>
                {
                    b.Navigation("WorkerOperations");
                });
#pragma warning restore 612, 618
        }
    }
}
